### PR TITLE
fix: App Crash on LoginFragment (double tap)

### LINKED ISSUE #1242: bug: Trying to enter Login screen twice crashes the app
**Describe the bug**
Trying to enter Login screen twice crashes the app

**To Reproduce**
1. Go to Login page
2. Tap on Login in Bottom Nav again
3. App crashes

**Expected behavior**
App does not crash

**Screenshots**
crash

**Crash log**
```
2019-03-07 19:27:46.601 31803-31803/com.eventyay.attendee E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.eventyay.attendee, PID: 31803
    java.lang.IllegalStateException: Fragment LoginFragment{3bfb136 (8835c986-94ef-4728-ac33-e6a256da19f0) id=0x7f0800f4} has null arguments
        at org.fossasia.openevent.general.auth.LoginFragment$$special$$inlined$navArgs$1.invoke(FragmentNavArgsLazy.kt:42)
        at org.fossasia.openevent.general.auth.LoginFragment$$special$$inlined$navArgs$1.invoke(Unknown Source:0)
        at androidx.navigation.NavArgsLazy.getValue(NavArgsLazy.kt:44)
        at androidx.navigation.NavArgsLazy.getValue(NavArgsLazy.kt:34)
        at org.fossasia.openevent.general.auth.LoginFragment.getSafeArgs(Unknown Source:28)
        at org.fossasia.openevent.general.auth.LoginFragment.showSnackbar(LoginFragment.kt:214)
        at org.fossasia.openevent.general.auth.LoginFragment.onCreateView(LoginFragment.kt:60)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2530)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:887)
        at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:2090)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1864)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1820)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1721)
        at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManagerImpl.java:147)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Smartphone Info:**

Device: Google Pixel
OS: Android 9 Pie

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by theLimitBreaker**
Fixes #1242 

Changes: 
Made the default snackbar message non null. Which was the reason 

Screenshots for the change:

### CODE REVIEW

File: app/src/main/res/navigation/navigation_graph.xml [hunk 1]
```diff
@@ -207,9 +207,9 @@
 
         <argument
             android:name="snackbarMessage"
+            android:defaultValue="null"
```
[the remark this answers is not in the document]
Comment (theLimitBreaker) [reply app/src/main/res/navigation/navigation_graph.xml]: umm thats what I did just used "null" word instead of " '' ' " . If  want would do that.

[the remark this answers is not in the document]
Comment (haroldadmin) [reply app/src/main/res/navigation/navigation_graph.xml]: I think it would help people understand the code better when they read it if the default value is something sensible, like a blank string. Using `"null"` technically works, but since it is not a standard value it might cause difficulty for people trying to understand the code later.

File: app/src/main/res/navigation/navigation_graph.xml [hunk 2]
```diff
@@ -60,9 +60,9 @@
 
         <argument
             android:name="time"
+            android:defaultValue="@null"
             app:argType="string"
-            app:nullable="true"
-            android:defaultValue="@null"/>
+            app:nullable="true" />
```
[the remark this answers is not in the document]
Comment (theLimitBreaker) [reply app/src/main/res/navigation/navigation_graph.xml]: I am sorry . I ran code format , It did that . reverting it now

File: app/src/main/res/navigation/navigation_graph.xml (hunk 1 above)
[the remark this answers is not in the document]
Comment (theLimitBreaker) [reply app/src/main/res/navigation/navigation_graph.xml]: For better readablity, I suppose , we should write "Not-Set", that's clear in first go

**Comment by theLimitBreaker** [comment]
@haroldadmin I updated it . review it

**Comment by haroldadmin** [comment]
@theLimitBreaker Can you please update the PR to resolve conflicts? Also, please change the default message to a blank string, and before displaying the Snackbar check if the message is blank using the `.isNotBlank()` stdlib function.

**Comment by theLimitBreaker** [comment]
Yes I was going to update . 
Regarding blank string. I thought setting default message to "not-set" would be more readable . 
Setting it to blank message this is the need

**Comment by theLimitBreaker** [comment]
@haroldadmin , setting "`''`" in nav-graph doesn't make it empty or blank string , instead it will show 
`''` as string in SnackBar .

**Comment by haroldadmin** [comment]
You can leave it as `""`. It shows a red line when you do this, but the project builds and runs just fine.

**Comment by theLimitBreaker** [comment]
That's not a good practice. Are you sure?

**Comment by haroldadmin** [comment]
@iamareebjamal @liveHarshit Need your opinion here

File: app/build.gradle [hunk 3]
```diff
@@ -152,8 +153,9 @@ dependencies {
     implementation 'com.journeyapps:zxing-android-embedded:3.6.0'
 
     //Navigation
-    implementation 'android.arch.navigation:navigation-fragment-ktx:1.0.0-rc02'
-    implementation 'android.arch.navigation:navigation-ui-ktx:1.0.0-rc02'
+    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version" // For Kotlin use
+    // navigation-fragment-ktx
+    implementation "androidx.navigation:navigation-ui-ktx:$nav_version"
```
Comment (liveHarshit) [inline app/build.gradle]: Why these changes?

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt [hunk 4]
```diff
@@ -211,8 +211,9 @@ class LoginFragment : Fragment() {
     }
 
     private fun showSnackbar() {
-        safeArgs.snackbarMessage?.let { textSnackbar ->
-            Snackbar.make(rootView.loginCoordinatorLayout, textSnackbar, Snackbar.LENGTH_SHORT).show()
+        val snackMessage = safeArgs.snackbarMessage
+        if (snackMessage != "not-set") {
+            Snackbar.make(rootView.loginCoordinatorLayout, snackMessage, Snackbar.LENGTH_SHORT).show()
```
Comment (liveHarshit) [inline app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: Just check snackMessage is `nullOrEmpty()`, Then only show the Snack bar. No need to compare strings. Also do not remove null safety.

File: app/build.gradle (hunk 3 above)
Comment (theLimitBreaker) [reply app/build.gradle]: migrate to androidX, It was using pre-androidX versions

Comment (liveHarshit) [reply app/build.gradle]: I don't think it relates to issue #1242. You can open a new issue for this.

File: app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt (hunk 4 above)
Comment (theLimitBreaker) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: actually if `snackmessage is set null` , `safeArgs itself become null`. Its Nav AAC issue,  
can't set @null to default value

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: Use empty string then, for default value.

Comment (theLimitBreaker) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: >haroldAdmin:  You can leave it as `""`. It shows a red line when you do this, but the project builds and runs just fine.
> thelimitbreaker: That's not a good practice. Are you sure?

Thats the issue. Further I think , setting a default value like 'not-set' (specifically in this case only) make it readable and understandable. Also No red lines, no bad practices

Comment (liveHarshit) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: What is the logic for red lines?

Comment (haroldadmin) [reply app/src/main/java/org/fossasia/openevent/general/auth/LoginFragment.kt]: I think the lint check just warns that there's no value set here. It's a warning, not a compilation error.
